# config for analysis

# most CPUs to ever use at once
max_cpus: 16

# amplicons sequenced by PacBio
amplicons: data/PacBio_amplicons.gb

# list of the primary targets for which we are calling mutations
mutated_targets:
  - AncSarbecovirus_MAP
  - AncAsia_MAP
  - AncSARS2a_MAP
  - AncSARS2c_MAP
  - SARS-CoV-2
  - SARS-CoV-2_2649
  - GD-Pangolin
  - RaTG13
  - AncSARS1a_MAP
  - Rs7327
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_2693
  - SARS-CoV-1_PC4-137_PC04
  - AncClade2_MAP
  - BM48-31

# groups and orders of targets for plotting
mutated_targets_ordered:
  - AncSarbecovirus_MAP
  - BM48-31
  - AncAsia_MAP
  - AncSARS2a_MAP
  - GD-Pangolin
  - AncSARS2c_MAP
  - SARS-CoV-2
  - RaTG13
  - AncSARS1a_MAP
  - Rs7327
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_PC4-137_PC04
  - AncClade2_MAP


targets_ordered:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - BM48-31
  - BtKY72
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS2c_MAP
  - SARS-CoV-2
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3


EurAf_extant:
  - BM48-31
  - BtKY72

SARS2_extant:
  - SARS-CoV-2
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  
SARS1_extant:
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084

Clade2_extant:
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3

ancestors_MAP:
  - AncSarbecovirus_MAP
  - AncAsia_MAP
  - AncSARS2a_MAP
  - GD-Pangolin
  - AncSARS2c_MAP
  - AncSARS1a_MAP
  - Rs7327
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncClade2_MAP
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  
ancestors_MAP_v_alt:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only

#indexing of mutated sites for mutated targets
mutant_indexing_file: data/mutated_target_indexing.csv  
  
# how to parse the amplicon
feature_parse_specs: data/feature_parse_specs.yaml

# do we get the sequencing data from the 'HutchServer' or 'SRA'?
seqdata_source: HutchServer

# list of PacBio sequencing runs linking barcodes to variants
pacbio_runs: data/PacBio_runs.csv

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

#annotations about RBD sites
RBD_annotation_file: data/RBD_sites.csv
 
# output directories / files
summary_dir: results/summary
anc_RBDs_dir: results/ancestral_RBD
ccs_dir: results/ccs
process_ccs_dir: results/process_ccs
processed_ccs_file: results/process_ccs/processed_ccs.csv
variants_dir: results/variants
nt_variant_table_file: results/variants/nucleotide_variant_table.csv
counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv
figs_dir: results/figures
merged_sequencing_dir: results/merged_sequencing
merged_sequencing_file: results/merged_sequencing/merged_sequencing_dt.csv
Titeseq_Kds_dir: results/binding_Kds
Titeseq_Kds_file: results/binding_Kds/binding_Kds.csv
expression_sortseq_dir: results/expression_meanFs
expression_sortseq_file: results/expression_meanFs/expression_meanFs.csv
final_variant_scores_dir: results/final_variant_scores
final_variant_scores_wt_file: results/final_variant_scores/wt_variant_scores.csv
final_variant_scores_mut_file: results/final_variant_scores/mut_variant_scores.csv


# parameters for running PacBio `ccs` program
min_ccs_accuracy: 0.999
min_ccs_passes: 3
min_ccs_length: 50
max_ccs_length: 5000

# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0
